services:
  web:
    build:
      context: ./front-end/
      dockerfile: Dockerfile
    image: "web_server"
    ports:
      - "9000:9000"
    depends_on:
      - api

  api:
    build:
      context: ./back-end/
      dockerfile: Dockerfile
    image: "api_server"
    ports:
      - "5252:5252"
